//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prs.appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class spravochnaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spravochnaya()
        {
            this.uchetnaya = new HashSet<uchetnaya>();
        }
    
        public int Kod_Tovara { get; set; }
        public string Nazvaniye_tovara { get; set; }
        public string Edinica_izmereniya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uchetnaya> uchetnaya { get; set; }
    }
}
