//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prs.appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class uchetnaya
    {
        public int Nomer_postuplenya { get; set; }
        public int Kod_tovara { get; set; }
        public string Data { get; set; }
        public string Cena { get; set; }
        public string Kolichestvo_tovara { get; set; }
    
        public virtual spravochnaya spravochnaya { get; set; }
    }
}
